updated bitrise.yml

diff --git a/bitrise.yml b/bitrise.yml
--- a/bitrise.yml
+++ b/bitrise.yml
@@ -5,35 +5,54 @@ app:
   envs:
   - RELEASE_VERSION: 0.9.0
 workflows:
-  _install-test-tools:
+  test:
+    before_run:
+    - go-tests
     steps:
-    - script:
-        title: Install required testing tools
+    - change-workdir@1.0.1:
+        inputs:
+        - path: ./_tmp
+    - script@1.1.4:
+        title: Create test file
         inputs:
         - content: |-
             #!/bin/bash
-            set -ex
-            # Check for unhandled errors
-            go get -u -v github.com/kisielk/errcheck
-            # Go lint
-            go get -u -v github.com/golang/lint/golint
-  audit-this-step:
-    steps:
-    - script:
-        inputs:
-        - content: |-
-            #!/bin/bash
-            set -ex
-            stepman audit --step-yml ./step.yml
-  create-release:
-    steps:
-    - script:
-        inputs:
-        - content: |
-            #!/bin/bash
+            # fail if any commands fails
             set -e
-            export CI=true
-            releaseman create --version $RELEASE_VERSION
+            # debug log
+            set -x
+
+            echo "test-content" > ./test-file.txt
+    - path::./:
+        title: Step Test
+        description: |-
+          The example input has a default value,
+          you can overwrite it if you want to, just like we did below,
+          but the step would use the default value specified in the `step.yml`
+          file if you would not specify another value.
+        run_if: "true"
+        inputs:
+        - directory_path: "./"
+        - touch_time: "2017-09-01T15:00:00+00:00"
+    - script@1.1.4:
+        title: Check if test file's mTime matches with the step's time
+        inputs:
+        - content: |-
+            #!/bin/bash
+            # fail if any commands fails
+            set -e
+            # debug log
+            set -x
+
+            if [ "$(stat -x "./test-file.txt" | awk -F': ' '/Modify: /{print $2}')" = "Fri Sep  1 15:00:00 2017" ];
+            then
+                     echo "All ok"
+                     exit 0
+            else
+                     echo "File time mismatch"
+                     exit 1
+            fi
+
   go-tests:
     before_run:
     - _install-test-tools
@@ -75,6 +94,39 @@ workflows:
             #!/bin/bash
             set -ex
             go test ./...
+
+  _install-test-tools:
+    steps:
+    - script:
+        title: Install required testing tools
+        inputs:
+        - content: |-
+            #!/bin/bash
+            set -ex
+            # Check for unhandled errors
+            go get -u -v github.com/kisielk/errcheck
+            # Go lint
+            go get -u -v github.com/golang/lint/golint
+
+  audit-this-step:
+    steps:
+    - script:
+        inputs:
+        - content: |-
+            #!/bin/bash
+            set -ex
+            stepman audit --step-yml ./step.yml
+
+  create-release:
+    steps:
+    - script:
+        inputs:
+        - content: |
+            #!/bin/bash
+            set -e
+            export CI=true
+            releaseman create --version $RELEASE_VERSION
+
   godeps-update:
     title: Godeps update
     description: |
@@ -129,50 +181,3 @@ workflows:
             bitrise share start -c ${MY_STEPLIB_REPO_FORK_GIT_URL}
             bitrise share create --stepid ${STEP_ID_IN_STEPLIB} --tag ${STEP_GIT_VERION_TAG_TO_SHARE} --git ${STEP_GIT_CLONE_URL}
             bitrise share finish
-  test:
-    before_run:
-    - go-tests
-    steps:
-    - change-workdir@1.0.1:
-        inputs:
-        - path: ./_tmp
-    - script@1.1.4:
-        title: Create test file
-        inputs:
-        - content: |-
-            #!/bin/bash
-            # fail if any commands fails
-            set -e
-            # debug log
-            set -x
-
-            echo "test-content" > ./test-file.txt
-    - path::./:
-        title: Step Test
-        description: |-
-          The example input has a default value,
-          you can overwrite it if you want to, just like we did below,
-          but the step would use the default value specified in the `step.yml`
-          file if you would not specify another value.
-        run_if: "true"
-        inputs:
-        - directory_path: "./"
-        - touch_time: "2017-09-01T15:00:00+00:00"
-    - script@1.1.4:
-        title: Check if test file's mTime matches with the step's time
-        inputs:
-        - content: |-
-            #!/bin/bash
-            # fail if any commands fails
-            set -e
-            # debug log
-            set -x
-
-            if [ "$(stat -x "./test-file.txt" | awk -F': ' '/Modify: /{print $2}')" = "Fri Sep  1 17:00:00 2017" ];
-            then
-                     echo "All ok"
-                     exit 0
-            else
-                     echo "File time mismatch"
-                     exit 1
-            fi
